### PR TITLE
Add support for resolving devices by partlabel and partuuid

### PR DESCRIPTION
**Pull request by tbzatek**
Inspired by @agners PR #861

### CODE REVIEW

**Review by vojtechtrefny — APPROVED** [review]
Looks good to me.

**Comment by agners** [comment]
@tbzatek thanks for picking this up :+1: 

LGTM.

**Comment by tbzatek** [comment]
Jenkins, test this please.

**Comment by tbzatek** [comment]
Jenkins, test this please.

**Comment by tbzatek** [comment]
Needs a fix in #955 to solve the failing new tests.

**Comment by tbzatek** [comment]
Jenkins, test this please.

**Pull request merged**
