### PR TITLE
udiskslinuxblockobject: Try issuing BLKRRPART ioctl harder

### LINKED ISSUE #1204: teardown fails on locked LUKS block dev: Call failed: Error synchronizing after initial wipe: Timed out waiting for object
About a week ago, cockpit's storage tests against the nightly udisks COPR [started to fail](https://github.com/cockpit-project/cockpit/issues/19445) in `testOverMounting`. This creates a GPT partition, a (really two, but that doesn't matter) LUKS partition on it, locks it, and then tries to re-format the whole device with tear-down. This works fine in Fedora 38's udisks2-2.9.4-7.fc38.x86_64, but fails with udisks2-2.11.0-1.20231011045721822941.master.73.g2fc7aae4.fc38.x86_64 from https://copr.fedorainfracloud.org/coprs/g/storage/udisks-daily

Pure CLI reproducer:

1. Update to daily COPR:
```
dnf -y copr enable @storage/udisks-daily; dnf -y --setopt=install_weak_deps=False update
```

2. Create a storage device. `scsi_debug` works fine:
```
modprobe scsi_debug dev_size_mb=100
```
This usually creates `/dev/sda`. If you already have that, it'll be a different one. The following reproducer assumes /dev/sda.

3. Format it with GPT:
```
busctl call org.freedesktop.UDisks2 /org/freedesktop/UDisks2/block_devices/sda org.freedesktop.UDisks2.Block Format 'sa{sv}' 'gpt' 0
```

4. Create a LUKS ext4 partition on it, with fstab/crypttab options and tracking parents:
```
busctl call org.freedesktop.UDisks2 /org/freedesktop/UDisks2/block_devices/sda org.freedesktop.UDisks2.PartitionTable CreatePartitionAndFormat 'ttssa{sv}sa{sv}' 0 50000000 '' '' 0 ext4 3 encrypt.type s luks2 encrypt.passphrase s foobar config-items "a(sa{sv})" 2      fstab 6 track-parents b true dir ay 9 47 114 117 110 47 102 111 111 0 type ay 5 97 117 116 111 0 opts ay 14 110 111  97 117 116 111  44 110 111 102  97 105 108 0 freq i 0 passno i 0      crypttab 2 options ay 14 110 111  97 117 116 111  44 110 111 102  97 105 108 0 passphrase-contents ay 1 0
```
This is quite a mouthful and hard to read due to the byte arrays.  I translated this from Cockpit's D-Bus call, whose JSON dump is this:

```json
[
    0,
    50000000,
    "",
    "",
    {

    },
    "ext4",
    {
        "tear-down": {
            "t": "b",
            "v": true
        },
        "encrypt.passphrase": {
            "t": "s",
            "v": "foobar"
        },
        "encrypt.type": {
            "t": "s",
            "v": "luks2"
        },
        "config-items": {
            "t": "a(sa{sv})",
            "v": [
                [
                    "crypttab",
                    {
                        "options": {
                            "t": "ay",
                            "v": "bm9hdXRvLG5vZmFpbAA="
                        },
                        "track-parents": {
                            "t": "b",
                            "v": true
                        },
                        "passphrase-contents": {
                            "t": "ay",
                            "v": "AA=="
                        }
                    }
                ],
                [
                    "fstab",
                    {
                        "dir": {
                            "t": "ay",
                            "v": "L3J1bi9mb28A"
                        },
                        "type": {
                            "t": "ay",
                            "v": "YXV0bwA="
                        },
                        "opts": {
                            "t": "ay",
                            "v": "bm9hdXRvLG5vZmFpbAA="
                        },
                        "freq": {
                            "t": "i",
                            "v": 0
                        },
                        "passno": {
                            "t": "i",
                            "v": 0
                        },
                        "track-parents": {
                            "t": "b",
                            "v": true
                        }
                    }
                ]
            ]
        }
    }
]
```

`opts`/`options` is `noauto,nofail`, `type` is `ext4`, `dir` is `/run/foo`. The crypttab `track-parents` option does not actually exist, so my CLI reproducer above does not contain it.

This creates a crypttab entry like
```
luks-8b81a135-59fa-4190-bd70-c61b40792128 UUID=8b81a135-59fa-4190-bd70-c61b40792128 none noauto,nofail
```
and an fstab entry like
```
UUID=10f5289e-f225-4c16-8d6c-d426db2bb893 /run/foo auto noauto,nofail,x-parent=8b81a135-59fa-4190-bd70-c61b40792128 0 0
```

5. Now lock the device (without that step, everything works):
```
busctl call org.freedesktop.UDisks2 /org/freedesktop/UDisks2/block_devices/sda1 org.freedesktop.UDisks2.Encrypted Lock 'a{sv}' 0
```

6. Try to reformat the drive:
```
busctl call org.freedesktop.UDisks2 /org/freedesktop/UDisks2/block_devices/sda org.freedesktop.UDisks2.Block Format 'sa{sv}' 'gpt' 1 'tear-down' b true
```

The latter will hang, and eventually fail with
```
Call failed: Error synchronizing after initial wipe: Timed out waiting for object
```

the journal says
```
udisksd[11637]: Locked device /dev/sda1 (was unlocked as /dev/dm-0)
udisksd[11637]: Error re-reading partition table (BLKRRPART ioctl) on /dev/sda: Device or resource busy
udisksd[11637]: Error synchronizing after initial wipe: Timed out waiting for object
```

Use `systemctl stop udisks2; rmmod scsi_debug` to clean up. Sometimes stopping udisks hangs, or scsi_debug is busy, but some combination of retrying these and calling `cryptsetup luksClose ...` works.

See https://github.com/cockpit-project/cockpit/issues/19445 for debugging details.

### PR DESCRIPTION
**Pull request by tbzatek**
For some reason even after acquiring a voluntary BSD lock on the device the BLKRRPART ioctl still fails with EBUSY. Wait a couple of msec and everything is fine.

So try harder, several attempts, if busy. There might be number of things going on in the system and it's out of our control even when holding a lock.

Fixes #1204

### CODE REVIEW

**Comment by tbzatek** [comment]
Jenkins, test this please.

**Review by vojtechtrefny — APPROVED** [review]
Looks good to me.

**Comment by mvollmer** [comment]
Just for the record, we have seen this as well in the Cockpit tests: https://github.com/cockpit-project/cockpit/pull/19574

Thanks for doing the retry on your level already!

**Comment by tbzatek** [comment]
> Thanks for doing the retry on your level already!

Later I realized it might have been some other UDisks thread that kept the device busy. We might perhaps need a global per-device lock... will see about that.

**Pull request merged**
