### PR TITLE
lvm2: Refactor udisks_daemon_util_lvm2_wipe_block()

### LINKED ISSUE #900: TODO: rewrite udisks_daemon_util_lvm2_wipe_block()
https://github.com/storaged-project/udisks/blob/2e114ad2e6c22f09a20853825e99aa73bc9d98e5/modules/lvm2/udiskslvm2daemonutil.c#L139-L142

* port to `bd_fs_wipe()`, the current code might work for MBR only
* use `udisks_linux_block_object_reread_partition_table()` instead of `ioctl (fd, BLKRRPART, NULL)`

https://github.com/storaged-project/udisks/blob/2e114ad2e6c22f09a20853825e99aa73bc9d98e5/modules/lvm2/udiskslvm2daemonutil.c#L226-L237
* port to libblockdev API, avoid calling commands directly (+ check throughout the rest of the lvm2 module)

### PR DESCRIPTION
**Pull request by tbzatek**
Legacy code, most of the stuff is now offered by the current API.

Fixes #900

### CODE REVIEW

**Review by vojtechtrefny — APPROVED** [review]
Looks good to me.

**Comment by martinpitt** [comment]
The [testTeardownRetry rawhide](https://artifacts.dev.testing-farm.io/42f44dfe-807e-4534-a817-dc5bb843e245/) failure is worth retrying (`/packit retest-failed` or click on "Re-run" [here](https://github.com/storaged-project/udisks/pull/1212/checks?check_run_id=18571508605)). I *think* it's an unrelated bug.

**Comment by tbzatek** [comment]
> The [testTeardownRetry rawhide](https://artifacts.dev.testing-farm.io/42f44dfe-807e-4534-a817-dc5bb843e245/) failure is worth retrying (`/packit retest-failed` or click on "Re-run" [here](https://github.com/storaged-project/udisks/pull/1212/checks?check_run_id=18571508605)). I _think_ it's an unrelated bug.

Okay, let's see. It's great that to have this caught by the reverse tests!

`RuntimeError: Timed out on 'set -e; [ -e /sys/module/scsi_debug ] || exit 0; for dev in $(ls /sys/bus/pseudo/drivers/scsi_debug/adapter*/host*/target*/*:*/block); do     for s in /sys/block/*/slaves/${dev}*; do [ -e $s ] || break;         d=/dev/$(dirname $(dirname ${s#/sys/block/}));         umount $d || true; dmsetup remove --force $d || true;     done;     umount /dev/$dev 2>/dev/null || true; done; until rmmod scsi_debug; do sleep 0.2; done'
`

Would be interesting to dump the state of block devices after such failure. `lsblk` and perhaps even `udisksctl dump` to see if there's any mess hanging around.

**Comment by tbzatek** [comment]
> The initial failure was a timeout in the UI. I'll look into that in the next days, sorry for the trouble.

Oh no worries, it's valuable to see how your testing framework works.

Let's merge this then and keep an eye on any related failures.

**Comment by martinpitt** [comment]
Sent https://github.com/cockpit-project/cockpit/pull/19605 to robustify this.

**Pull request merged**
