### PR TITLE
update DocBook DTD version to latest stable 4.5

### PR DESCRIPTION
**Pull request by kloczek**

### CODE REVIEW

**Comment by StorageGhoul** [comment]
Can one of the admins verify this patch?

**Comment by tbzatek** [comment]
Jenkins, ok to test.

**Review by tbzatek — APPROVED** [review]
Looks good, `docbook-xml-dtd-4.5` was released back in 2006.

**Review by vojtechtrefny — APPROVED** [review]

**Comment by kloczek** [comment]
Thank you 👍

**Pull request merged**
