### PR TITLE
fstab records escaping

### PR DESCRIPTION
**Pull request by tbzatek**
This is an attempt to provide sane and consistent `/etc/fstab` parsing and identifier matching to align with `mount` command escaping rules. This includes various combination of quotes and spaces for `LABEL=` and `PARTLABEL=` identifiers.

Affects mostly users of `udisks_linux_block_matches_id()`.

TODO:
 * verify `util-linux`' `blkid_parse_tag_string()` symbol deprecation
 * have a look at crypttab and utab parsing

### CODE REVIEW

**Comment by tbzatek** [comment]
`utab` parsing should be all covered as it uses `libmount` to read the table. `crypttab` parsing is a problem however, opened #889 for that in the meanwhile as it's a very low priority.

**Review by vojtechtrefny — COMMENTED** [review]
Looks good to me, the `blkid_parse_tag_string` function is great.

**Comment by tbzatek** [comment]
Jenkins, test this please.

**Comment by tbzatek** [comment]
Jenkins, test this please.

**Review by vojtechtrefny — APPROVED** [review]

**Pull request merged**
