### PR TITLE
main.c: Properly remove sigint source

### PR DESCRIPTION
**Pull request by azzar1**
Revert https://github.com/storaged-project/udisks/commit/d9f7b05bf73ab193c8778a8bb34e52e0e677c0a4 and properly fix the critical warning.

### CODE REVIEW

**Comment by azzar1** [comment]
The old code path was causing several crash reports on Ubuntu (https://errors.ubuntu.com/problem/93775674877696284083874f33927631ec531a70). I'm not even source removing this kind of source is really required.

**Comment by vojtechtrefny** [comment]
Jenkins, ok to test.

**Comment by vojtechtrefny** [comment]
> I'm not even source removing this kind of source is really required.

The documentation for this is not really helpful. I'll try to ask few GNOME people how this should work, but I think you might be right and we might not need to remove the source. But removing it shouldn't be a problem.
Thank you for fixing this.

@tasleson Can you check this change too please, you are author of the original fix.

**Comment by vpodzime** [comment]
Potentially fixes #417

**Comment by tasleson** [comment]
Are we getting the message again:

`STDERR:
GLib-CRITICAL **: Source ID 1 was not found when attempting to remove it` with this change reverted?

**Comment by tasleson** [comment]
I'm OK with reverting this change as having an error message is better than a seg. fault, but we should investigate why we are getting the original error message.

**Comment by vojtechtrefny** [comment]
> Are we getting the message again:
> STDERR: GLib-CRITICAL **: Source ID 1 was not found when attempting to remove it with this change reverted?

No, it's no in the test logs. The [G_SOURCE_CONTINUE](https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#G-SOURCE-CONTINUE:CAPS) in the SIGINT handler prevents autoremoving the source so it can be removed by us later in `main`.

**Comment by tasleson** [comment]
Are we running the tests with `export G_DEBUG=fatal_warnings` or `export G_DEBUG=fatal_criticals`, the later might be good thing to do.

**Comment by vojtechtrefny** [comment]
> Are we running the tests with export G_DEBUG=fatal_warnings or export G_DEBUG=fatal_criticals, the later might be good thing to do.

No, but we have an issue for that #264

**Comment by vojtechtrefny** [comment]
Thanks again @azzar1

**Pull request merged**
