### PR TITLE
Fix loop device setup

### LINKED ISSUE #580: “Timed out waiting for object” trying to mount a partition inside an image
Not sure this is the proper place to report to as I couldn't find similar issues but hopefully you'll show me out if this is not the right place.

On Ubuntu 18.04, I am now getting errors mounting an image file while it used to work properly in the past.

```
kelson@camber:/tmp$ udisksctl loop-setup --offset 7000031744 --size 55532878336 --file /media/backup/plug-2018_09_18-22_49_34.ERROR.img --no-user-interaction
Error setting up loop device for /media/backup/plug-2018_09_18-22_49_34.ERROR.img: GDBus.Error:org.freedesktop.UDisks2.Error.Failed: Error waiting for loop object after creating /dev/loop5Timed out waiting for object
```

* the image has been created with `qemu-img`.
* The offset matches the third partition (exfat) of a 3 partitions table.
* I have been mounting images using the above command for a long time without any issue.
* Since this Sunday, I am getting the mentioned error message.
* I am getting this out of a freshly started system.

Logs
[udevadm-info.txt](https://github.com/storaged-project/udisks/files/2397161/udevadm-info.txt)
[udiskctl-dump.txt](https://github.com/storaged-project/udisks/files/2397162/udiskctl-dump.txt)
[mountinfo.txt](https://github.com/storaged-project/udisks/files/2397163/mountinfo.txt)
[gvfs-mount-li.txt](https://github.com/storaged-project/udisks/files/2397164/gvfs-mount-li.txt)
[gvfs-mount-io.txt](https://github.com/storaged-project/udisks/files/2397165/gvfs-mount-io.txt)
[udevadm-monitor.txt](https://github.com/storaged-project/udisks/files/2397166/udevadm-monitor.txt)

### LINKED ISSUE #800: test_loop_ro tests failing
The test has been consistently failing with 2.9.x on the current Ubuntu serie

https://autopkgtest.ubuntu.com/packages/u/udisks2/groovy/amd64

https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-groovy/groovy/amd64/u/udisks2/20200901_002642_d9555@/log.gz
```
======================================================================
ERROR: test_loop_ro (__main__.Manager)
loop device R/O
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src/tests/integration-test", line 637, in test_loop_ro
    (path, out_fd_list) = self.manager.call_loop_setup_sync(
gi.repository.GLib.GError: udisks-error-quark: GDBus.Error:org.freedesktop.UDisks2.Error.Failed: Error waiting for loop object after creating '/dev/loop0': Timed out waiting for object (0)
```
The fixes in 2.9.1 don't seem to make a difference

some others are also flaky still and the errors from https://github.com/storaged-project/udisks/issues/777#issuecomment-642515509 don't seem resolved

### LINKED ISSUE #817: Timed out waiting for object
I am trying to mount iso. But I am getting this error

`$ udiskie-mount Win10_2004_English_x64.iso
failed to add Win10_2004_English_x64.iso: GDBus.Error:org.freedesktop.UDisks2.Error.Failed: Error waiting for loop object after creating '/dev/loop4': Timed out waiting for object`
and
`$ udisksctl loop-setup -r -f Win10_20H2_English_x64.iso
Error setting up loop device for Win10_20H2_English_x64.iso: GDBus.Error:org.freedesktop.UDisks2.Error.Failed: Error waiting for loop object after creating '/dev/loop5': Timed out waiting for object`

Mount works for smaller iso. It works in Arch linux iso. But big iso(windows iso, office img files) files have this mounting problem. I have wipe out and reinstalled system. Still this problem exists. I have seen people complaining about this error in reddit and other forums. ex: [reddit](https://www.reddit.com/r/linux4noobs/comments/jntn0n/cant_mount_isos_in_popos_2004/), [manjaro forum](https://forum.manjaro.org/t/iso-not-mounting/34964)

[udisksctl_dump.txt](https://github.com/storaged-project/udisks/files/5531648/udisksctl_dump.txt)
[udevadm.txt](https://github.com/storaged-project/udisks/files/5531658/udevadm.txt)
[mountinfo.txt](https://github.com/storaged-project/udisks/files/5531662/mountinfo.txt)
[fstab.txt](https://github.com/storaged-project/udisks/files/5531669/fstab.txt)

### LINKED ISSUE #828: Can not setup loop device for ISO file because of time out waiting for object
```
$ udisksctl loop-setup -r -f myISOfile.iso

Error setting up loop device for myISOfile.iso: GDBus.Error:org.freedesktop.UDisks2.Error.Failed: Error waiting for loop object after creating '/dev/loop0': Timed out waiting for object
```

```
$ ls /dev/loop*
/dev/loop0  /dev/loop1  /dev/loop2  /dev/loop3  /dev/loop4  /dev/loop5  /dev/loop6  /dev/loop7  /dev/loop-control
```

Once I repeat the command `udisksctl loop-setup -r -f myISOfile.iso` , the loop device  from the error message will change to /dev/loop1, /dev/loop2, and so on. It won't be successful until /dev/loop8.

### PR DESCRIPTION
**Pull request by tbzatek**
This will trigger extra uevent after loop device setup to ensure all objects are updated.

Resolves #800 
Resolves #817
Resolves #580
Resolves #828

### CODE REVIEW

**Review by vojtechtrefny — APPROVED** [review]
Looks good to me.

**Comment by tbzatek** [comment]
Changed wording of an error message...

Anyway, I'm still thinking about reworking uevent trigger a little bit... Historically we've been getting sysfs path from a `GUdevDevice` instance, either by holding a reference within `UDisksLinuxBlockObject` or by querying actual udev db. Only to get a sysfs path for the device, the actual trigger was always done by writing to that sysfs file.

What we can do is to bypass udev and construct the sysfs path manually, avoiding potential race from udev holding either old device path or none (yet) at all. In most of the cases the path construction would be pretty straightforward, however we might need to resolve device symlinks in some cases. In particular the `lvm2` module will hit the issue (see my last commit in #814).

**Review by vpodzime — APPROVED** [review]
Hate to see things like this being added to UDisks, but it's the only realistic way of fixing things. ACK.

**Comment by tbzatek** [comment]
> Hate to see things like this being added to UDisks, but it's the only realistic way of fixing things. ACK.

Yeah, we tend to generate too many uevents, basically every intrusive operation is followed by explicit uevent trigger. That's in place already over majority of the damon methods. It's the most reliable way however to ensure everything is up-to-date.

**Comment by gramozeka** [comment]
ya sobral predlozhennoye ispravleniye, no oshibka ostalas'.
vozmozhno chto-to ya delayu ne tak ili ne khvatayet kakikh-to zavisimostey, no eto ne rabotayet
142/5000
I put together the suggested fix, but the bug persists.
maybe i'm doing something wrong or missing some dependencies, but it doesn't work

`udisksctl loop-setup -r -f  image.iso
Error setting up loop device for image.iso: GDBus.Error:org.freedesktop.UDisks2.Error.Failed: Error waiting for loop object after creating '/dev/loop2': Timed out waiting for object
`
I attach the conclusion strace maybe this will help in finding a solution.
[test.txt](https://github.com/storaged-project/udisks/files/5614415/test.txt)

**Comment by tbzatek** [comment]
@gramozeka, have you built and ran the daemon with the fix? `strace`-ing `udisksctl` is pointless as it's just a D-Bus client.

**Comment by gramozeka** [comment]
> have you built and ran the daemon with the fix?

yes, I used a branch udisks-8d5c90a1f4bbe548a1ae361f8d69970669d6e72e, the problem is not in the code udisks, the problem is new kernel breaks. With the kernel 5.4.XX everything works fine, both the stable version udisks-2.9.1 and that version with fixes.
I don't know what the core writers have done, obviously crooked hands are a steady trend of our time)

**Review by vojtechtrefny — APPROVED** [review]
Still looks good to me. Hope it actually fixes the issues :-)

Could we add some test case for this? (Something more reliable than the "randomly broken" `test_loop_ro` from #800?)

**Comment by tbzatek** [comment]
TODO: https://github.com/storaged-project/udisks/blob/master/src/udisksstate.c#L631

**Comment by tbzatek** [comment]
> Could we add some test case for this? (Something more reliable than the "randomly broken" `test_loop_ro` from #800?)

Hmm, do you have any suggestion? I can't think of any test that would actually raise the error to test the negative case. This commit fixes the `org.freedesktop.UDisks2.Manager.LoopSetup()` method call that is tested via several `test_loop.UdisksLoopDeviceTest` tests.

**Comment by tbzatek** [comment]
Actually found another tiny bug in my code, hard to hit in real use case scenarios though...

**Pull request merged**
