### PR TITLE
udiskslinuxfilesystem: New 'allow-multi' option for Mount.

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
One could argue that UDisks itself should know whether multi-mounting makes sense or not, and behave accordingly without any special option... E.g., btrfs with different subvol options can be multi-mounted, but xfs can not.

**Comment by blivetghoul** [comment]
Can one of the admins verify this patch?

**Comment by mvollmer** [comment]
Let's keep this a draft... I am more and more certain that Cockpit will stop using UDisks2 for mounting and unmounting.

**Comment by mvollmer** [comment]
> Let's keep this a draft... I am more and more certain that Cockpit will stop using UDisks2 for mounting and unmounting.

Let's just close this, until I change my mind.

**Pull request closed without merging**
