### PR TITLE
use g_shell_quote for inputs to g_shell_parse_argv

### PR DESCRIPTION
**Pull request by maltek**
Fixed version of https://github.com/storaged-project/udisks/pull/623 - one should really test again after changing "only cosmetic" things.

### CODE REVIEW

**Comment by vojtechtrefny** [comment]
Jenkins, ok to test.

**Comment by maltek** [comment]
@tbzatek Note that the escaped commands are never actually sent to an actual shell, only to `g_shell_parse_argv` (in `UDisksSpawnedJob`). If the commands were used with a real shell, the old code would have been open to all kinds of privilege escalation attacks because they execute commands within ``` `` ``` or `$()` - but glib does not. Avoiding such attacks in case the code changes in the future is my prime motiviation for this pull request.

What kind of test do you want me to write? That arbitrary strings round-trip correctly the call chain `udisks_daemon_util_subst_str_and_escape -> g_shell_parse_argv`?

**Comment by vpodzime** [comment]
> What kind of test do you want me to write? That arbitrary strings round-trip correctly the call chain `udisks_daemon_util_subst_str_and_escape -> g_shell_parse_argv`?

ping @tbzatek

**Comment by tbzatek** [comment]
> What kind of test do you want me to write? That arbitrary strings round-trip correctly the call chain `udisks_daemon_util_subst_str_and_escape -> g_shell_parse_argv`?

Hmm, right, that doesn't make much sense on the second look. Please disregard that.

Anyway, could you addess @vpodzime's concern about the commit message please? We'll merge it afterwards.

**Comment by tbzatek** [comment]
Jenkins, test this please.

**Comment by tbzatek** [comment]
ping @vpodzime, can we merge this? :-)

**Pull request merged**
