### PR TITLE
Make libatasmart support optional

### PR DESCRIPTION
**Pull request by Thaodan**

### CODE REVIEW

**Comment by blivetghoul** [comment]
Can one of the admins verify this patch?

**Comment by tbzatek** [comment]
I'm sorry, but `GDBus` method invocations require different handling in case of an unsupported call.

Additionally there is a plan to move ATA SMART handling to libblockdev making it a plugin. As a benefit there might be multiple implementations to choose from, e.g. `libatasmart` and `smartmontools`. If you want to contribute that way, you're welcome to start a new `libblockdev` plugin and start moving the functionality from `udisks` there.

Also please note we'll be adding more library dependencies in the future, such as `libnvme` (that has its own set of required dependencies) once released.

Please continue in #433.

**Comment by Thaodan** [comment]
> Also please note we'll be adding more library dependencies in the future, such as `libnvme` (that has its own set of required dependencies) once released.

Then please make them optional, there are usecases where devices don't have ata or nvme interfaces making libnvme redundant.

**Comment by tbzatek** [comment]
Yes, we thought about that and decided not to make `libnvme` optional. It will include NVMeoF initiator and just like the existing ATA drive support the functionality will be a part of the core daemon interfaces. It's not simply something that could be easily made conditional. Don't worry, `libnvme` is rather tiny.

**Pull request closed without merging**
