### PR TITLE
80-udisks2.rules: fix warnings reported by udevadm verify

### PR DESCRIPTION
**Pull request by ldv-alt**
Fix the following warnings reported by udevadm verify:

```
data/80-udisks2.rules:84 Whitespace after comma is expected.
data/80-udisks2.rules:85 Whitespace after comma is expected.
data/80-udisks2.rules:88 Whitespace after comma is expected.
data/80-udisks2.rules:89 Whitespace after comma is expected.
data/80-udisks2.rules:90 Whitespace after comma is expected.
data/80-udisks2.rules:169 Whitespace after comma is expected.
data/80-udisks2.rules: udev rules check failed
```

### CODE REVIEW

**Comment by StorageGhoul** [comment]
Can one of the admins verify this patch?

**Review by vojtechtrefny — APPROVED** [review]
Thank you.

**Comment by tbzatek** [comment]
Jenkins, ok to test.

**Review by tbzatek — APPROVED** [review]
Nice, thanks!

(FWIW, these card reader stuff should've long been moved somewhere else, we were hoping that `sid` would materialize by now, that didn't happen. Perhaps there is similar database somewhere else...)

**Pull request merged**
