### PR TITLE
Add 'windows_names' as a default mount option for ntfs-3g

### LINKED ISSUE #620: Add windows_names as a default mount option for ntfs-3g
I think it's a good idea to add 'windows_names' as a default mount option for ntfs-3g. The main reason of being able to use ntfs on linux is interoperability with windows operating system. However, I would personally run into problems when copied a bunch of files from my ext4 filesystem to my ntfs flashdrive and because of the naming convention had to go through irresponsive filesystem and fixing it with chkdsk.exe everytime on windows OS. This led to some files being moved to a garbage folder with arbitrary namings which took even further effort to find what is what in that folder to find my files.

### PR DESCRIPTION
**Pull request by A-Shahbazi**
This fixes #620

### CODE REVIEW

**Comment by vpodzime** [comment]
Jenkins, this is ok to test.

**Comment by vpodzime** [comment]
> Looks good to me too, we should bring attention on this change in the release notes.

Btw, any release planned soon?

**Comment by vpodzime** [comment]
> Looks good to me too, we should bring attention on this change in the release notes.

Btw, any release planned soon?

**Comment by tbzatek** [comment]
> Btw, any release planned soon?

Yes, today or Monday at the latest. Need to check couple of gtk-doc warnings.

**Pull request merged**
